// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QApp.Database;

namespace QApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181125022454_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("QApp.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Email");

                    b.Property<bool>("Enabled");

                    b.Property<bool>("IsAdmin");

                    b.Property<DateTime>("ModifiedUtc");

                    b.Property<string>("Name");

                    b.Property<string>("PasswordHash");

                    b.Property<Guid>("PasswordSalt");

                    b.Property<bool>("ResetPassword");

                    b.Property<string>("SessionToken");

                    b.Property<DateTime>("SessionTokenExpiresUtc");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
